#!/bin/bash
NAME=`hostname |cut -d . -f 1`
ADDRP=`host $NAME 192.168.0.1|grep has|cut -f4 -d" "`
ADDRX=`host $NAME.private 192.168.0.1|grep has|cut -f4 -d" "`
PUB="Ethernet 1"
MD="Ethernet 2"
networksetup -setmanual "$PUB" $ADDRP 255.255.255.0 192.168.0.255
networksetup -setdnsservers "$PUB" 192.168.0.1 192.168.0.1
networksetup -setsearchdomains "$PUB" local
networksetup -setmanual "$MD" $ADDRX 255.255.255.0

systemsetup -setusingnetworktime on
systemsetup -setnetworktimeserver "192.168.0.1"
